### ISSUE TITLE
RVD Business Logic

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RaveAddIn#101]
Looks like we already have business logic for RVD

https://github.com/Riverscapes/RaveAddIn/blob/master/RaveAddIn/XML/rvd.xml

We should just do a quick test to make sure it's up to date with what's coming out of cybercastor.

**Comment by philipbaileynar** [comment]
I can confirm that the initial version of RVD business logic is working in RAVE 2.0.2. Symbology still needed.

<img width="1000" alt="Screen Shot 2021-01-26 at 12 41 49 PM" src="https://user-images.githubusercontent.com/8645379/105902769-f3536880-5fd3-11eb-8455-14607eecafd9.png">
