### ISSUE TITLE
Project Metadata Not Loading on Topo Projects

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#103]
## The Problem
![image](https://user-images.githubusercontent.com/9723905/104495813-71a41980-5595-11eb-8268-214500898a97.png)

What went wrong?
Exception thrown when you view Project MetaData

## Reproduction steps

1 Loaded [Asotin Topo Project](https://data.riverscapes.xyz/#/AsotinIMW/9caeb350-596b-445e-b3a9-8b4f813598d6)
2. Then attempted to get project metadata

Exception message

```text

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index must be within the bounds of the List.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.ObjectModel.Collection`1.Insert(Int32 index, T item)
   at RaveAddIn.ucProjectExplorer.OnMetaData(Object sender, EventArgs e) in

**Comment by philipbaileynar** [comment]
@joewheaton I can't reproduce this.

I even tried making sure that the topo project was the second project in the list because it looks like you have a hydraulic modelling project in there too.

I got the exact same projects too.

Perhaps a quick video please? Or wait and try again on the next release that is iminent.

**Comment by philipbaileynar** [comment]
How recently did you download this project?

Have you made any edits to the project XML?

Any custom business logic at play?

If in doubt please download fresh copy.

**Comment by joewheaton** [comment]
Yep... corrupted local project. Would be interesting to know why someday. But I got it to work on other Topo projects.  Thanks @philipbaileynar
