### ISSUE TITLE
GUT Business Logic - plumb layer files

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#105]
@philipbaileynar wrote us nice Riverscape Projects for GUT and a version of GUT that exposes what is in those files.  @wally-mac please have @Cashe93 or whomever use this ticket to tie the pull request to (re-assign from yourself to them). This is tied the [Basecamp ToDo](https://public.3.basecamp.com/p/N1WAPyjLD4v4ZL6JDB5sYH7f)

**Comment by wally-mac** [comment]
@Cashe93  I've assigning this task to you. @tyler1218hatch please help Cashe on this as needed.  Thanks!

**Comment by philipbaileynar** [comment]
I just release version 2.0.3 of RAVE that includes Cashe's pull request containing business logic and lots of layer files. @joewheaton described this as 95% of what's needed. Here's his video describing the outstanding items

https://youtu.be/-SU3FLcbzCk

**Comment by wally-mac** [comment]
@Cashe93 can you please address the outstanding items Philip points out in his video?  Thanks for providing this Philip

**Comment by Cashe93** [comment]
@philipbaileynar, do we still need to save layer files as version 10.4?

**Comment by philipbaileynar** [comment]
Good question... I am on 10.6.1 now. So technically you should choose nothing newer than 10.6.1 as the version. I think 10.4 will still work because all our existing symbology works for me. 

What are the options newer than 10.4?

**Comment by Cashe93** [comment]
Sounds good. The options newer than 10.4 are 10.5 and 10.6.

**Comment by philipbaileynar** [comment]
OK, go with 10.6 from now on then.

No reason to redo any of the existing layer files.

**Comment by philipbaileynar** [comment]
@Cashe93 please close this issue if the work is complete. I know 90% of the layers are how @joewheaton wants them, I'm just uncertain if we are all the way there?

**Comment by Cashe93** [comment]
@philipbaileynar, I have a short list of changes that @joewheaton  would like to be made. I don't think these will get it to 100% satisfaction but I'll close this after I make the changes and the pull request is reviewed.

**Comment by Cashe93** [comment]
@philipbaileynar, I'm sorry this took so long for me to get to. I've just submitted a pull request/review on the changes.

**Comment by philipbaileynar** [comment]
Fixed as part of release 2.1.1
