### ISSUE TITLE
QGIS Version of RAVE

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#108]
As with #107 we need a QGIS Version of RAVE. @philipbaileynar has already scoped this and we simply need to raise the funds to do it. 

I am posting this here @philipbaileynar so we can start cataloging our wish list items more consistently. These are excerpts from @philipbaileynar Scope (minus price tag):

## Background
We stopped maintaining a prior version ([website](https://riverscapes.github.io/RiverscapesToolbar/) and [repo](https://github.com/Riverscapes/RiverscapesToolbar)) of RAVE approximately 3 years ago and have been exclusively working on an ArcGIS based version of this software. The goal of this work is to resurrect the QGIS code, upgrade it to the latest version of QGIS and produce a new version of the software that integrates with our existing RAVE business logic. 

At a high level, the prior version of QGIS RAVE performed two distinct functions:
1) it displayed the contents of an online data warehouse and helped the user download projects to their computer, and 
2) it helped the user add layers from these projects to their current map document, along with consistent symbology. 

### 1. Professional-Grade QGIS RAVE 

RAVE for QGIS with the following features: 
- Open riverscapes projects and present the project tree in a dockable window using existing business logic XML. 
- Add one or more project layers to the current map document without symbology. In other words, QGIS will apply the default symbology to all layers (grey scale rasters, random colors for vectors). 
- Allow the user to add basemap web mapping services to the map. 
- Leverage “project views” defined in business logic. 
### 2. Enhance QGIS RAVE to apply symbology defined in QML files. 

This will work much like the layer files in ArcGIS but instead will use the QML standard that QGIS already uses for storing symbology. This task requires that task 1 also be funded. Note that this does not affect ArcGIS RAVE, which will continue to use the existing layer files. 

### 3. Enhance QGIS RAVE to show the contents of a riverscapes data warehouse and download projects onto the user’s computer, from where they can then be added to the current map document. 

This task requires that task 1 also be funded (but not necessarily task 2). 

### 4. Enhance ArcGIS RAVE to use the same QML symbology files that QGIS RAVE will use. 

This means doing away with the proprietary ESRI layer files and entirely migrating ArcGIS RAVE to use the open standard as QGIS RAVE.

**Comment by joewheaton** [comment]
So just an update:
- 1 & 2 These are now done with https://github.com/Riverscapes/QRAVEPlugin!

**Comment by philipbaileynar** [comment]
Closing because outstanding issues moved to #137
