### ISSUE TITLE
Fix Symbology for BRAT Management Layers

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#111]
We recently enhanced BRAT so that it only produces a GeoPackage as the output. No ShapeFiles.

Unfortunately this has broken the symbology for the three management layer outputs. That was originally working. Can you please fix the three management layer files with the correct symbology. It's all pinks and pastels right now until this gets fixed.

The three files that need fixing are:

- oPBRC_CR.lyr
- oPBRC_UD.lyr
- oPBRC_UI.lyr

Here's an example of what it currently looks like:

<img width="1361" alt="Screen Shot 2021-01-26 at 4 05 50 PM" src="https://user-images.githubusercontent.com/8645379/105923172-cfeae680-5ff0-11eb-98ee-362ab8c96dfa.png">

**Comment by Cashe93** [comment]
@philipbaileynar, just to clarify, for this task are you just asking that I update the symbology to something similar to the attached image? 
![image](https://user-images.githubusercontent.com/49880208/106083536-e28d1a80-60d9-11eb-8c68-8818d2131450.png)

**Comment by philipbaileynar** [comment]
Yes that's correct. Same colours and labels. 

After we moved to geopackages all the colours broke.

**Comment by philipbaileynar** [comment]
This is now working!
