### ISSUE TITLE
Automated version checking

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#113]
How do we inform users when there's a new version of RAVE?

1. Users sign in to GitHub and click "watch" on the repo to receive notifications. Most users aren't that technical. I also believe that this means they will get issue notifications as well as releases. Too noisy!
2.  We use MailChimp or similar to announce releases. I don't have time to craft these messages! Too noisy.
3. Automated software check for current version. The latest release of the software is available online at the two following places:

## ESRI metadata describing the AddIn

This file is nice because it's machine readable XML. See line 5 for version number.

[https://raw.githubusercontent.com/Riverscapes/RaveAddIn/master/RaveAddIn/Config.esriaddinx](https://raw.githubusercontent.com/Riverscapes/RaveAddIn/master/RaveAddIn/Config.esriaddinx)

# C# file that describes the version of the AddIn DLL file

This file is C#... we really don't want to parse this file!

[https://raw.githubusercontent.com/Riverscapes/RaveAddIn/master/RaveAddIn/Properties/AssemblyInfo.cs](https://raw.githubusercontent.com/Riverscapes/RaveAddIn/master/RaveAddIn/Properties/AssemblyInfo.cs)

## Recommendation

One approach would be to check the version containing in the Config.esriaddinx when the AddIn loads. I **don't** think we should do this. The AddIn DLLs actually load when ArcGIS starts up. Any warning message would appear for all users that have the RAVE installed, even if they are not using or have forgotten about RAVE. At best this would be annoying. At worst, any bugs in our checking code would crash ArcGIS (trust me... been there).

Instead I think we add a "Check For Updates" button on the RAVE help menu that performs the version check all wrapped in try/catch handling for safety.

![2021_01_28_145019](https://user-images.githubusercontent.com/8645379/106208434-38b09b00-6178-11eb-8c71-9c33751265b3.png)

Thoughts?

**Comment by MattReimer** [comment]
I like the menu item. We definitely want our code to avoid phoning home without asking. 

My suggestion would be a quick call to the github api:

### Docs and code samples:

https://docs.github.com/en/rest/reference/repos#get-the-latest-release

### Example

paste this into your browser:
```
https://api.github.com/repos/Riverscapes/RaveAddIn/releases/latest
```

Something like this:

```csharp
 HttpClient client = new HttpClient();
 HttpResponseMessage response = await client.GetAsync("https://api.github.com/repos/Riverscapes/RaveAddIn/releases/latest");
 response.EnsureSuccessStatusCode();
 string responseBody = await response.Content.ReadAsStringAsync();
```


### Resources

* https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client

**Comment by philipbaileynar** [comment]
With @MattReimer help we got the HTTP call with SSL working to check the latest version via GitHub:

https://gist.github.com/philipbaileynar/36b385e75400e6ba788b2ca2f70ce5c4

The code above works perfectly in this standalone, console application. But when I implemented this code in RAVE it hangs during the asynchronous call. I suspect (and vaguely recall) something about ArcMap being a single threaded application that can't handle asynchronous code. 

Will spend a bit more time researching ArcGIS and multi-threading and then abandon this idea. Too bad....

**Comment by MattReimer** [comment]
We could just make it a synchronous call. The only reason I keep it async is because I don't like to lock up the ui.

**Comment by joewheaton** [comment]
Thanks @MattReimer and @philipbaileynar for investigating this. As I see this was assigned for input from me....  I'm of a little use on the technical issue @MattReimer found but...

> Instead I think we add a "Check For Updates" button on the RAVE help menu that performs the version check all wrapped in try/catch handling for safety. Thoughts?

I love it. Nice compromise.

**Comment by joewheaton** [comment]
I think that with the arcRAVE 2.2 release, the decision is made above to make it consistent with QRAVE. I think some of this becomes less important now too that we'll be updating resources instead of updating. This is redundant with #137
