### ISSUE TITLE
RVD Symbology

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#114]
RVD business logic is now implemented. We also have lots of [RVD symbology layer files](https://github.com/Riverscapes/RaveAddIn/tree/master/RaveAddIn/Symbology/RVD) that are already included with RAVE. However, the layer files refer to the old attribute fields from pyRCAT. Most of the fields names have changed now that RVD is using a GeoPackage.

Tasks Required:

1. Walk through each of the layers referred to in the [RVD business logic](https://github.com/Riverscapes/RaveAddIn/blob/master/RaveAddIn/XML/rvd.xml) and assign them the symbology attribute for the appropriate layer file.
2. Check that the layer file refers to the correct attribute field.

Note that step 2 is fiddly. Changing the attribute field that a layer refers to seems to reset the symbol classes and you have to rebuild them by scratch (annoying for RVD which has some layers with lots of symbol classes). I have not found a workaround for within ArcGIS for changing the attribute field while retaining the symbol classes.

FYI. This issue came out of the [riverscapes tool to fix RVD project file](https://github.com/Riverscapes/riverscapes-tools/issues/189).

**Comment by tyler1218hatch** [comment]
@philipbaileynar I think Wally and I are going to discuss plans for this soon. I think he wanted to change some of the symbology in both versions anyways.

**Comment by joewheaton** [comment]
This belongs over in RiverscapesXML. Started new: https://github.com/Riverscapes/RiverscapesXML/issues/171
