### ISSUE TITLE
Installation instructions for QRAVE

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#143]
Please record a little video and provide some brief installation and update instructions for QRAVE [here](https://github.com/Riverscapes/RaveAddIn/blob/master/docs/install.md#qgis-plug-in)

**Comment by joewheaton** [comment]
See https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/Common.html if you need a refersher on MD edits of site documentation. @shelbysawyer I am assigning this to you as it is a small task, and get you in the habit of preparing website documentation, which you will be doing shortly for VBET.

**Comment by shelbysawyer** [comment]
@joewheaton @MattReimer A few questions:
- What is the minimum version requirement for QRAVE to work in QGIS?
- If the QRAVE Plug-In has already been installed, is the "update resources" option enough to pull the latest release?

**Comment by joewheaton** [comment]
> @joewheaton @MattReimer A few questions:
> 
> * What is the minimum version requirement for QRAVE to work in QGIS?

Get confirmation from @MattReimer, but I think it is [3.16](https://github.com/Riverscapes/QRAVEPlugin/issues/16)? 

> * If the QRAVE Plug-In has already been installed, is the "update resources" option enough to pull the latest release?

No. All that does is get the latest business logic and symbology from RiverscapesXML. To install the latest release, you go to the Plugin Manager (it will also likely give you a notification). Bare in mind that the QRAVE plugin will not be updated that regularly. When it does, you do the following.

To update, go Plugins → Plugin Manager and search for Riverscapes Plugin (QRAVE). It will list Installed Version and Available Version. If not the same, it will have an option to update. If latest, it can be uninstalled, or reinstalled. 
![image](https://user-images.githubusercontent.com/9723905/127707171-c50257fa-0bb2-444f-a65a-42c1064ae873.png)

**Comment by shelbysawyer** [comment]
@joewheaton Ah, I thought so. Mine was already updated, so I wasn't able to see what a user with an outdated version would see. Thanks!

**Comment by shelbysawyer** [comment]
@joewheaton One more question before I do the pull request: On the RAVE website homepage, the "Download RAVE" button takes viewers to the Esri Add-In download. I want to 1) add a button to download the QRAVE Plug-In called "Download RAVE for QGIS" and 2) edit the existing button to say "Download RAVE for ArcGIS"

The problem is that I couldn't find the md file to make these changes. Where is it?

**Comment by joewheaton** [comment]
> On the RAVE website homepage, the "Download RAVE" button takes viewers to the Esri Add-In download. I want to 1) add a button to download the QRAVE Plug-In called "Download RAVE for QGIS" and 2) edit the existing button to say "Download RAVE for ArcGIS"

That [button](https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/styleguide.html#buttons) is on the home page and is just a little bit of html:

```
<div style="text-align:center">
<a class="button large" href="https://github.com/Riverscapes/RaveAddIn/releases/latest">
        <img src="{{site.baseurl}}/assets/images/RiverscapesLogo_x16.png">
        &nbsp;&nbsp;Download RAVE</a>
</div>
```

The `<div>` tags are just to center it. If you want the changes you mentioned, do something like:
```
<div style="text-align:center">
<a class="button large" href="http://rave.riverscapes.xyz/install.html#qgis-plug-in">
        <img src="{{site.baseurl}}/assets/images/RiverscapesLogo_x16.png">
        &nbsp;&nbsp;Installation Instructions for QRAVE PlugIn for QGIS</a>
<a class="button large" href="https://github.com/Riverscapes/RaveAddIn/releases/latest">
        <img src="{{site.baseurl}}/assets/images/RiverscapesLogo_x16.png">
        &nbsp;&nbsp;Download ArcRAVE AddIn for ArcGIS 10.X</a>
<a class="button large" href="https://data.riverscapes.xyz">
        <img src="{{site.baseurl}}/assets/images/RiverscapesLogo_x16.png">
        &nbsp;&nbsp;Explore WebRAVE in Warehouse/a>
</div>
```
Note that I added three buttons in above and they go to different places. Technically, QGIS is not downloaded for installation, so hence the link to the "install" instructions. Also, WebRAVE is not yet live and public, but when it is ready, it will just be part of the warehouse. Also, I used same icon <img> for all, but that can be updated later when we hire the graphic designer. 
 
> The problem is that I couldn't find the md file to make these changes. Where is it?

So all these jekyll-git-hosted sites have a [`index.md`](https://github.com/Riverscapes/RaveAddIn/blob/master/docs/index.md) in the root directory that represents the home page.

**Comment by shelbysawyer** [comment]
> Technically, **QGIS is not downloaded for installation**, so hence the link to the "install" instructions. Also, WebRAVE is not yet live and public, but when it is ready, it will just be part of the warehouse. Also, I used same icon  for all, but that can be updated later when we hire the graphic designer.

@joewheaton I'm confused about this-- my understanding is that to get QRAVE, users have to download the qrave_toolbar.zip from the repo, and then install QRAVE as a Plug-In in QGIS, just as they need to with the RAVE Add-In for ArcGIS. I thought the only difference was that the QRAVE Plug-In only needed to be downloaded and installed once (with updating done within QGIS) versus the uninstall, re-download, reinstall process needed to update the RAVE Add-In for ArcGIS. If QRAVE is not downloaded for installation, then what's the proper process?

**Comment by joewheaton** [comment]
Nope... see [this video](https://youtu.be/O5xwIqhtlag)

In fact, you could just embed it as the instructions ;). https://youtu.be/O5xwIqhtlag

**Comment by shelbysawyer** [comment]
@joewheaton Thanks!

**Comment by joewheaton** [comment]
@shelbysawyer I fixed this.
