### ISSUE TITLE
Backslashes (windows) break Linux/OSX

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#152]
This issue originated in [riverscapes-tools/issues/367#issuecomment-893891369](https://github.com/Riverscapes/riverscapes-tools/issues/367#issuecomment-893891369). 

@MattReimer said this a problem in all versions of RAVE, so this is the sister post to https://github.com/Riverscapes/QRAVEPlugin/issues/30 for ArcRAVE:

ArcRave should be able to handle windows slashes in project files, even on mac.

> 
> example:
> ```
> <Raster guid="9e5b9cb9-cbad-40ce-99fd-dbe100552bac" id="DEM">
>     <Name>DEM</Name>
>     <Path>inputs\dem.tif</Path>
> </Raster>
> ```
> On a Mac or linux this will be a path not found.
>

**Comment by philipbaileynar** [comment]
@joewheaton what does this mean?

> ArcRave should be able to handle windows slashes in project files, even on mac.

Arc only runs on Windows... Hopefully you're not thinking Parallels on a Mac? We've been down this road with GCD. Supporting products living in ESRI within virtualization environments is an endless nightmare of pain.

Also, has anyone actually reported a bug in ArcRAVE? Backslashes must already work, surely? Forward slashes?

**Comment by joewheaton** [comment]
Dough... That makes sense ☺️
