### ISSUE TITLE
ArcRave not bringing in Bankfull Island Symbology in GUT

### ISSUE THREAD

**Issue by CHafen** [Riverscapes/RaveAddIn#161]
It looks like ArcRAVE isn't bringing in the bankfull Island symbology for this GUT project.
The one circled in red is what RAVE brought it in as and the one circled in yellow is when I put the bfIslands.lyr file in to check what the symbology should be. I'm not sure who to tag here @joewheaton @MattReimer 
![bfIslands_symbology](https://user-images.githubusercontent.com/39837888/132411650-57df9241-ef01-414e-8ba9-b8a86020d5eb.png)

**Comment by MattReimer** [comment]
Hey @CHafen I moved this issue over into RaveAddin. 

ArcRave is currently way behind QRave and we're working hard to bring it up to speed. Let's sit on this issue and we can see if it's still a problem after the next version pushes out.

**Comment by CHafen** [comment]
@MattReimer I found the the issue with this. It's just a spelling error. The business logic symbology says "bfIlsands" instead of "bfIslands"

**Comment by MattReimer** [comment]
Cool. Are you cool to fix this or do you want me to do it?

**Comment by CHafen** [comment]
@MattReimer  I'll do it
