### ISSUE TITLE
Resource File Cleanup

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#166]
The new "update resource" feature currently only downloads files. It also needs the ability to remove files that are no longer in the RiverscapesXML manifest. This is most important for symbology because curators might move a layer file from a tool specific folder to the shared folder. In these situations the local copy in the tool specific folder needs to get removed or it will take precedence over the shared copy!

**Comment by MattReimer** [comment]
Just for completeness here's the python:
https://github.com/Riverscapes/QRAVEPlugin/blob/master/src/classes/net_sync.py#L169-L180
