### ISSUE TITLE
Not Zooming to Project

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#179]
both @joewheaton and @lauren-herbine noted that ArcRAVE is not zooming to a project extent when first adding layers.

I don't think this was ever a feature? It never did this zooming?

If we really want this, perhaps we limited it to adding a project to the map and there are no other layers in the map (i.e. the user has not interacted with the map and set an extent that they want. In other words, we are not trampling on an extent they have already set)

**Comment by joewheaton** [comment]
@lauren-herbine this _is_ not a RAVE feature, but is just a feature in both QGIS and ArcGIS, of when you add the first layer to the map with data, it zooms to the extent of that data. If you open a project in an existing map, it will not zoom to it. I don't think we need this.
