### ISSUE TITLE
'Find Resources Folder' broken in this release

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#180]
Just noticed that 3.1 does not take us to the resources folder. Just goes to AppData/Roaming?

**Comment by philipbaileynar** [comment]
This is working for me. I suspect that your RAVE folder doesn't exist yet? See the code below.

```c#
string app_data = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
if (Directory.Exists(app_data))
{
    string rave_data = Path.Combine(app_data, Properties.Resources.AppDataFolder);
    if (Directory.Exists(rave_data))
        System.Diagnostics.Process.Start(rave_data);
    else
        System.Diagnostics.Process.Start(app_data);
}
else
    MessageBox.Show("The system APPData folder does not exist.", "AppData Folder Missing", MessageBoxButtons.OK, MessageBoxIcon.Information);
```

**Comment by joewheaton** [comment]
Okay, I can't check this right now (don't have ArcGIS working on this machine). However, could the error message be a little more helpful? Most users have no idea what their AppData folder is. Can you tell them what they need to do to get RAVE to make it for them?
