### ISSUE TITLE
Stop Shipping Resources and Instead Check For Resources

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#181]
1. ArcRAVE should no longer ship with business logic and layer files.
2. When the user clicks the "Open Project" button, ArcRAVE should check if the resource folder exists and if not offer to refresh the resources, warning the user that resources are needed to view the project.

The rationale for number 1 above is that ArcRAVE releases will get less frequent now that we don't need to do a release every time business logic or symbology changes. This means that the copy of the resources that ships with the software could be woefully out of date and desirable. If a user forgets to ever check for resources they could be using 6 month old business logic!

The rationale for number 2 above is that we need an event to trigger the prompt to check for resources. We do not want to automatically check for resources when ArcRAVE loads, because this happens when ArcGIS starts up. If something goes wrong with the call over the internet for resources, ArcGIS will crash and essentially cripple the user's ArcGIS installation.

**Comment by joewheaton** [comment]
Seems like you fixed this with https://github.com/Riverscapes/RaveAddIn/releases/tag/3.2.0 and https://github.com/Riverscapes/RaveAddIn/commit/e36b47738199daa9981b1e795930cf7859e264d8?

**Comment by philipbaileynar** [comment]
Yes.
