### ISSUE TITLE
Update Warehouse links to new system

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RaveAddIn#188]
This ticket should only be done AFTER the final migration from the temporary URL of https://warehouse.riverscapes.net to https://data.riverscapes.net

We need the projects to be able to link up to the new warehouse (Exchange). This should be a simple string substitution

**Comment by joewheaton** [comment]
Merci beaucoup @MattReimer!

**Comment by philipbaileynar** [comment]
See below. Also, I did a search for the word "warehouse" in the .net solution and found not code results.

<img width="848" alt="Screenshot 2023-08-01 at 8 47 07 AM" src="https://github.com/Riverscapes/RaveAddIn/assets/8645379/c4b66279-3c73-4c57-bf12-12d306040672">
