### ISSUE TITLE
Update Icon for Viewer Site to Viewer Icon

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#190]
@philipbaileynar maybe you can teach me how to do this by adding a documentation page to https://developer.riverscapes.net on how to do this?

![image](https://github.com/Riverscapes/RaveAddIn/assets/9723905/84c1b7c4-08d7-4eb6-b502-6e1b06fe5755)

**Comment by philipbaileynar** [comment]
I can't recall whether we can change favicon. Might need to talk to Michael.

**Comment by joewheaton** [comment]
Can we elevate this please @philipbaileynar?

**Comment by philipbaileynar** [comment]
Main logo is updated.

favicon is a [known issue](https://github.com/Riverscapes/riverscapes-gatsby-theme/issues/18) across all sites that use our Gatsby theme.
