### ISSUE TITLE
Other Files in project tree

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#21]
We need the ability to have other files in the RAVE project explorer. e.g.:

* Images
* Databases
* Spreadsheets

The default bevaviour is to attempt the open the file in question. If this fails then simply open the folder in which the file resides.

**Comment by joewheaton** [comment]
Other obvious ones:
- Text files
- PDFs

**Comment by joewheaton** [comment]
Good test for BRAT will be to take the `Summary Products' folder and make the PNGs and PDFs visible at same place in tree as project GIS Data (even though they are in a duplicated folder location).

**Comment by philipbaileynar** [comment]
This is implemented but there's a bug causing the files not to open.
