### ISSUE TITLE
Some incremental updates to VBET input business logic

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#23]
Hey @philipbaileynar I've updated the business logic and created some 10.4 compliant layer files to go along with it. 

![image](https://user-images.githubusercontent.com/9723905/81034593-e34b9580-8e54-11ea-8cf0-987aabffd94f.png)

[vbet-lyr.zip](https://github.com/Riverscapes/vbet/files/4578887/vbet-lyr.zip)
[vbet-businesslogic.zip](https://github.com/Riverscapes/vbet/files/4578891/vbet-businesslogic.zip)

**Comment by joewheaton** [comment]
Seems like you incorporated all these.

Quick question @philipbaileynar. Can we force display order in TOC (different than #14) so that "Drainage Network" comes above "Lines of Evidence"?

**Comment by philipbaileynar** [comment]
@joewheaton I actually think this is a bug. Drainage Network appears above the evidence in the project tree therefore it should be above it in the ToC.
