### ISSUE TITLE
RAVE project loading log

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#26]
When developing business logic, it can be infuriatingly hard to know what's going on, why datasets don't load in the project tree, which business logic is being used etc.

It would be invaluable if RAVE produced a log file stating which business logic it used and what happened during NODE and Children parsing. Basically help developers know why stuff is missing from the tree!

**Comment by joewheaton** [comment]
And like you have with GCD, it would be really handy if what was written to log file is also displayed at bottom of dockable window in status bar.

**Comment by joewheaton** [comment]
So nice that QGIS does this already.  @philipbaileynar we should discuss if this is still relevant.

**Comment by philipbaileynar** [comment]
I really like the QGIS implementation. It's complex and expensive to build in ArcGIS. It's also less relevant now that most eyeballs are on QRAVE not ArcRAVE. @joewheaton please close this issue if you agree.

**Comment by joewheaton** [comment]
I agree @philipbaileynar. Not a priority if the primary audience is targeting our curators as they are all getting converted to Q junkies :)
