### ISSUE TITLE
TOC Sort Order and Business Logic

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#28]
In #23 we discussed whether sort order should be coming from business logic (see also #14, which is more complicated):

> @joewheaton I actually think this is a bug. Drainage Network appears above the evidence in the project tree therefore it should be above it in the ToC.

I opened this Bug as @philipbaileynar said that's what it was and we really already completed what #23 was about.

**Comment by philipbaileynar** [comment]
After using RAVE for over a year this has dropped off the radar. We have improved business logic across all project types and people are not mentioning this problem. I'm also not seeing people mention it as a problem during live demos and meetings etc.

At a fundamental level we do have the problem that vector layers lower down in the business logic get added to the map below rasters that are higher up in the business logic. This is inevitable given the design of the software.

I'm closing this issue until I hear people squawk on this topic.

Note #34 also relates to ToC order.

**Comment by joewheaton** [comment]
I am fine with this being closed @philipbaileynar. I really liked the idea you raised in our call last week for webRAVE about 5ish stashes...  from top of TOC to Bottom (e.g. Vector Points, Vector Polylines, Basemap Vector, Transparent Raster, Hillshade, Basemap vector). 

I don't think this entirely applies to RAVE as ArcGIS users know how to move around the layers and layer groups and can push past it. I do think we have two bad and unhelpful habits:
- Add All Layers to Map - I see lots of people use this and the only way it is useful to me is if all get added without being turned on.
- Project Views - with too many layers turned on.

**Comment by philipbaileynar** [comment]
Both your bullets refer to "visibility", something we don't (but could) control in business logic. Interesting idea that warrants more thought. Project views in particular would benefit from controlling visibility.

**Comment by joewheaton** [comment]
Yes... I guess there is a lot of value in having things in the TOC sometimes, but not necessarily all turned on with visibility. Good point @philipbaileynar.
