### ISSUE TITLE
What is the correct xsi:noNamespaceSchemaLocation to use?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#30]
Thanks @philipbaileynar and @MattReimer for the helpful [guidelines on XML editing](https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/Riverscapes_Projects/xml_validation.html). In it, you say:

> Ensure that the XML file refers to a schema namespace in the root XML tag of the file. Here’s an example from the top of a riverscapes project file referring to the XSD file online in the GitHub repository.

While I understand *what* you are saying, I have no idea what is the correct one to use or how to request or add myself new tags etc. Do you have this documented somewhere already or can you point us newbies in the right direction?

**Comment by philipbaileynar** [comment]
I will enhance the validation file to refer to the existing documentation:

* [The Project XML page already describes which one to use](https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/Riverscapes_Projects/Project/projectxml.html)
* The [RAVE toolbar does worse job describing the XSD location](http://rave.riverscapes.xyz/business-logic.html), but I will enhance this later today. Here's the official URL for RAVE business logic XSD:

[https://raw.githubusercontent.com/Riverscapes/RaveAddIn/master/RaveAddIn/XML/XSD/project_explorer.xsd](https://raw.githubusercontent.com/Riverscapes/RaveAddIn/master/RaveAddIn/XML/XSD/project_explorer.xsd)

**Comment by philipbaileynar** [comment]
Talked to with @MattReimer and everything is a bit scattered. There are several versions floating around dating back to the CHaMP days. We are actively consolidating all varieties of the XSD and will post updated URLs early next week.

The one XSD that is stable and will not change is the [RAVE business logic XSD](https://raw.githubusercontent.com/Riverscapes/RaveAddIn/master/RaveAddIn/XML/XSD/project_explorer.xsd).

**Comment by MattReimer** [comment]
Here's the deal: All XSD and XML examples are now in a new repo:

https://github.com/Riverscapes/RiverscapesXML

We now serve all XSD files from here
http://xml.riverscapes.xyz/

The new URLS look like this. 

http://xml.riverscapes.xyz/Projects/XSD/V1/VBET.xsd

For now you can create the paths by finding the XSD you need in github and using that same path at the end of http://xml.riverscapes.xyz/

The Riverscapes/Program repo has been deleted.

If you see `NorthArrowResearch/riverscapes-programs` in any urls that will eventually need to be changed but must remain for now until the refactor of the Warehouse has finished and we've updated all the projects inside the warehouse.

**Comment by philipbaileynar** [comment]
Closing this issue following Matt's detailed response. Re-open and assign to me if this still requires clarification.
