### ISSUE TITLE
Add All Layers to Map

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#31]
right clicking on project node in RAVE toolbar and choosing "add all layers to map" does not work properly for @kbartelt inundation project shared on 7 May 2020 via box. The layers get added to the map without symbology and then there's an exception at the end of the process.

**Comment by joewheaton** [comment]
Note... I also have same problem. The layers do all get added, but they do not have symbology.

**Comment by philipbaileynar** [comment]
I actually don't think that this feature is broken. The problem seems to be that some raster symbology layers are not working properly. Since most projects have raster layers this problem is most likely to manifest itself when you throw all the layers of a project at a map.

I will close this issue if we can't recreate this issue after the next RAVE release.

**Comment by philipbaileynar** [comment]
Remember to test intermediate "branch" "add all children" to tree as well.

**Comment by joewheaton** [comment]
> I will close this issue if we can't recreate this issue after the next RAVE release.

Sorry, just confirming that [1.1.0](https://github.com/Riverscapes/RaveAddIn/releases/latest) has same behavior.

**Comment by kbartelt** [comment]
I tested this with intermediate branches of the RAVE tree and had the same issue

<iframe width="560" height="315" src="https://www.youtube.com/embed/Y3v0p-0DUvA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by philipbaileynar** [comment]
OK, I will try and reproduce. Right now I can't add any rasters to the map because most of the symbology is broken for me on 10.4. I can try to figure out a workaround. I will shout if I can't reproduce this. Thanks @kbartelt  for the video.
