### ISSUE TITLE
Can we add TIN as a Node Data Type?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#32]
I'm making the Topo business logic and realize that TINs are not one of current four recognized [node data types](http://rave.riverscapes.xyz/business-logic.html#node-data-types). Can we add them so that TINs get added in ArcGIS RAVE?

**Comment by MattReimer** [comment]
Just for reference:
https://github.com/Riverscapes/RiverscapesXML/blob/master/Projects/XSD/V1/RiverscapesProject.xsd#L186-L190

**Comment by joewheaton** [comment]
Thanks @MattReimer. So I try:
` <Node xpathlabel="Name" xpath="Realizations/Topography/TIN/WaterSurfaceTIN[@id='WaterSurfaceTIN']" type="TINType" symbology="" />`

And it still can't add it. Hmmm.

**Comment by MattReimer** [comment]
Sorry Joe, that reference was mainly for @philipbaileynar when he goes to implement this.

We'll need to support that node type in Rave and push out a new version. I'll leave the rest to Philip.

**Comment by joewheaton** [comment]
Understood... Also, thinking that I should be using the name instead from here:
https://github.com/Riverscapes/RiverscapesXML/blob/master/Projects/XSD/V1/RiverscapesProject.xsd#L112-L137

However, I take your point.... it 'aint plumbed yet. Thanks.
