### ISSUE TITLE
Error When Adding to Map with Layer File in ToC

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#34]
See @kbartelt video where she tries to add a RAVE dataset to the map while having a layer file in the ArcMap ToC.

[![RAVE Issue](https://img.youtube.com/vi/GAjZvng5TM8/0.jpg)](https://www.youtube.com/watch?v=GAjZvng5TM8 "RAVE Issue")

**Comment by philipbaileynar** [comment]
@kbartelt can you report if this is still an issue? A lot has changed in RAVE since May 2020.

If the problem has not reoccurred recently please close this issue.

**Comment by kbartelt** [comment]
this is no longer an issue
