### ISSUE TITLE
Curated Views - The real thing

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#46]
In #45, @philipbaileynar proposed the idea of **highlighted views** as a way of promoting common views of the primary outputs or (TOC collection) for a map view of a riverscapes project. This is really powerful and applies to **all** projects of a specific riverscapes project type (e.g. BRAT, GUT, VBET). What we need is a concept that applies to the *specific* riverscapes project that someone has spent extra time curating (i.e. calibrating, validating, massaging inputs, interpreting outputs, producing cartographic outputs, writing reports, etc.). Think of **highlighted views** as empowering the model developer/owner to share common looks at their models, whereas *curated views* empowers model-users to tell a story with their own *specific* riverscapes project.

# What does that mean?
This is very much like the concept of an abstract or graphical abstract for a specific published paper.  An abstract asks the author (in this case the author of a specific riverscapes project) to highlight for the consumer (i.e. someone viewing RS project in RAVE or online) the key points and most important things. This is NOT the most common and typical ways of looking at that RS project type (i.e. #45 on *higlighted views*). This is instead things like:
- Articulated the why (note that RS projects [aim to define the what, who, how and when automatically](https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/Riverscapes_Projects/#riverscapes-projects) by way of metadata)
- Shared the significance of this output - *what does it really mean** 
- Provide any summary interpretation
- Highlight any reports, papers, publications that this RS project is used in or based on
- Provide way to cite this RS Project (including DOI)

# So where to do it?

I think these are things that get stored in the `project_rs.xml` but that get populated with a little helper tool (even in RAVE). 

Thoughts @philipbaileynar and @wally-mac or rest of team...?

**Comment by wally-mac** [comment]
@CHafen This might be something within your wheelhouse. Please have a look at what Joe has provided and feel free to reach out to him for further clarification.

**Comment by philipbaileynar** [comment]
Note that [project views](http://rave.riverscapes.xyz/business-logic.html#project-views) (#45) is now a feature in version 1.2 of RAVE.

**Comment by joewheaton** [comment]
So we can close this now I think @philipbaileynar ?
