### ISSUE TITLE
broken links when opening map 

### ISSUE THREAD

**Issue by sshahverdian** [Riverscapes/RaveAddIn#49]
When opening an existing map in Arcmap all files that were added to the map using RAVE and a riverscapes context project had broken links (red exclamation points).

**Comment by joewheaton** [comment]
Can you please reproduce this behavior with a video? Add stuff out of project to map. Save mxd. Close reopen and show what's happening. I have not had this happen and you don't provide enough detail to troubleshoot. If it on user side we need to pinpoint so we can write better documentation or help them avoid. If it is a real big, we need to reproduce it to fix it. Thanks!

**Comment by sshahverdian** [comment]
Sending you an 2 videos in an email attachment - it doesn't appear that the problem is with RAVE or .rs projects themselves - but I could still use some help troubleshooting whatever is going on.

**Comment by philipbaileynar** [comment]
I have not seen this behaviour. @joewheaton I wonder if arcmap is storing that it has a layer file in the table of contents and not the actual dataset that we end up pointing the layer at. 

Scott do you need map documents at all? Can you just use RAVE to reload from an empty map document during each session. If you have additional layers in the map then just save the document. But when you reload simply remove the top level rave item and reload using rave. 

Really looking forward to seeing the videos. I have a bad feeling that this is a legit issue and is the death knell for layer files in rave.

**Comment by sshahverdian** [comment]
@philipbaileynar I reproduced the issue once, when the map document was being opened from Box, but when I saved the map document on my desktop everything worked fine - see both videos. Hopefully it's not a RAVE issue, but since I work off of Box, I need to get it sorted regardless. 

Re: map documents - I can re-open from RAVE and no, it's not a huge deal for me. But as soon as I need to share a map document with others, it's helpful to have the full map available, and with a table of contents laid out in a certain way for others to view/manipulate.

[broken_link_videos.zip](https://github.com/Riverscapes/RaveAddIn/files/4673953/broken_link_videos.zip)

**Comment by philipbaileynar** [comment]
Were you switching between computers Scott? Is there a chance that the files had not synched down from box at first?

I know this sounds lame but actively editing files residing in synchronization software is fraught with problems. Especially if more than one person is using them at the same time.

**Comment by sshahverdian** [comment]
I wasn't switching between computers. No one else was editing these files.

In both cases the .rs projects were on Box, however the .mxd was saved to different locations in the two cases - once on my desktop, once on Box. The .mxd on box showed that it was in fact synched when I re-opened it on Box. 
Re: editing files on synchronization software - I'm happy to take any and all advice, whatever is best practice is what I'm hoping to do.

**Comment by joewheaton** [comment]
From @sshahverdian :
## Broken Links:
[![](http://img.youtube.com/vi/zs0bJUZoopw/0.jpg)](http://www.youtube.com/watch?v=zs0bJUZoopw "")

## Not-Broken Links:
[![](http://img.youtube.com/vi/W-SSXtjrelw/0.jpg)](http://www.youtube.com/watch?v=W-SSXtjrelw "")

**Comment by joewheaton** [comment]
So @philipbaileynar , we went through this and we should both be aware of this issue for Box Drive users (i.e. watch Scott's videos). I don't  think this is a RAVE problem, but just a GIS problem of working with Box Drive (which uses a virtual ISO map, and creates illusion of things on disc), and most places this was causing problems for Scott were folders that he did not have checked for "offline use" or synced locally. I explained that you can get things to work sometimes without offline use, and that syncing the folder of all the files you are referencing will work most the time. However, Arc will break inconsistently with Box Drive and best practice is to work locally outside of Box Drive and then copy any changes you want to keep when done over to Box as backup (something @wally-mac and I instituted as a lab policy a while back). 

I'm just documenting this as our fix and notifying you. Leaving breadcrumbs here in case it recurs for others.
