### ISSUE TITLE
Topo TIN not working in 1.1.0

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#59]
In 1.1.0, TINs now work! Yay! However, only the Water Surface TIN is currently plumbed in the business logic. We need to do same for Topo TIN.

**Comment by philipbaileynar** [comment]
Make sure you are using the business logic that ships with the software. I fixed this in 1.1.0 release.

**Comment by joewheaton** [comment]
Good catch... you were right. I had an old residual `topo.xml` in the root of the project. Tested and works now.
