### ISSUE TITLE
Some of the Channel Units don't have required fields

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#61]
## The Problem
Some of the topo projects have channel units with out the grain size fields and Hawkins Channel Units. These exist burried in the ChannelUnits.csv, but we need a a way to automate the spatial join.

![image](https://user-images.githubusercontent.com/9723905/83599761-371bce00-a52a-11ea-8ac5-5d7a0e2dc128.png)

**Comment by philipbaileynar** [comment]
@joewheaton in the grand waterfall of CHaMP data, the grain size fields are calculated after the topo survey is processed. They might be present in some surveys, but typically these values were unavailable when crews were processing surveys as they were part of the aux metric process. Some historical surveys might have them if they were reprocessed after the fact.

I have all the grain size metrics in the CHaMP Workbench database, but it will take someone a modest amount of scripting effort to inject them into the right place within topo projects.

**Comment by joewheaton** [comment]
Cool... should we leave it in business logic and change label to have (if present) and (if joined) and then leave this as enhancement for a rainy day?

**Comment by philipbaileynar** [comment]
Yeah I like that. Bigger fish to fry!

**Comment by philipbaileynar** [comment]
Duplicate in #87 #86 and #60
