### ISSUE TITLE
BRAT Business Logic Rasters should be consistent with RS Context

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#62]
## The Problem
The BRAT business logic should not have its own different Topography symbology for DEM, Slope, Drainage Area and Flow Accumulation. It should just use same as RS_Context. This is fixed by referring to same symoblogy keys and making sure it uses layers in the Common folder.

**Comment by tyler1218hatch** [comment]
@joewheaton I don't see symbology for drainage area or flow accumulation in the 'shared' folder. Should I add them in by copying from RS_Context? Or just directly reference the RS_Context Folder?

**Comment by joewheaton** [comment]
> @joewheaton I don't see symbology for drainage area or flow accumulation in the 'shared' folder.
That's right. They are in the [`rs_context`](https://github.com/Riverscapes/RaveAddIn/tree/master/RaveAddIn/Symbology/RSContext) folder. You'll need to move them in a new branch to Shared, and update BRAT business logic symbology keys accordingly. Make sense?

**Comment by tyler1218hatch** [comment]
Yes, that makes sense. When writing in the symbology name in the BRAT XML, is there a specific way to tell it to look in the Shared folder? Or will it look there as long as it can't find what it's looking for in the BRAT symbology folder?

**Comment by joewheaton** [comment]
@philipbaileynar  can confirm, but my understanding is there are a bunch of places RAVE looks for the symbology key (i.e. name of layer file) to use. It grabs the first one it can find (which can make it hard to troubleshoot). The search order/preference is:
- Local Project
- Local `AppData/RAVE/Symbology/ProjectType` folder
- Local  `AppData/RAVE/Symbology/Shared` folder
- RAVE hidden installation folder (i.e. ships with RAVE)`/ProjectType` folder
- RAVE hidden installation folder (i.e. ships with RAVE)`/Shared` folder

I think it just grabs the first one it finds. So in answer to your question, it keeps looking until it finds something. If it doesn't find anything, it just adds with default ESRI symbology.
