### ISSUE TITLE
VBET Business Logic Round 2

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#63]
## The Problem
We need to update the VBET business logic to be more consistent with the Riverscape Context. Special care should be made to use symbology keys that are common and in `Shared`, and to use consistent labels. Namely:
- [ ] Drainage Network should use same as Hydrography in RS_Context
- [ ] Slope Raster should be same as Slope Analysis
- [ ] HAND Raster is same but label needs updating
- [ ] Intermediate Thresholds should all be hollow... maybe play with some different things. 
- [ ] VBET Network should be moved back to Drainage Network Inputs

This will be iterative. Try some things, post them here for me to give you feedback on and make as separate commits to a VBET-bl-2 branch you create.

**Comment by philipbaileynar** [comment]
Let me try increasing your permissions

**Comment by Cashe93** [comment]
Thanks @philipbaileynar. Let me know what I can/need to do on my end.

**Comment by philipbaileynar** [comment]
Please try again @Cashe93

**Comment by Cashe93** [comment]
That seems to have worked. Thanks @philipbaileynar!

**Comment by Cashe93** [comment]
@joewheaton could you elaborate a bit more on 'Drainage Network should use same as Hydrography in RS_Context'? Did you want the contents of VBETs Drainage Network  to match the contents of Hydrography from RS Context? i.e. same shapefiles, labeling and symbology?

**Comment by Cashe93** [comment]
@joewheaton I just submitted a pull request. I've placed the symbology layers for the intermediate thresholds in the VBET symbology folder (within the VBET-bl-2 branch).

**Comment by joewheaton** [comment]
Sorry for slow reply @Cashe93 ... been slammed.

> @joewheaton could you elaborate a bit more on 'Drainage Network should use same as 
Hydrography in RS_Context'?

I just mean to copy the same business logic over. We have the same files for the network in both places, so might as well just bring in those business logic nodes under the Hydography:
![image](https://user-images.githubusercontent.com/9723905/83931959-d6280c00-a75c-11ea-9dcd-434c3db5651d.png)
.

> Did you want the contents of VBETs Drainage Network to match the contents of Hydrography from RS Context? i.e. same shapefiles, labeling and symbology?

Exactly. And those layer files can just be moved into Shared.

**Comment by Cashe93** [comment]
Hey @joewheaton, how do I request a review on changes I've made to a branch with an existing pull request?

**Comment by joewheaton** [comment]
> @joewheaton could you elaborate a bit more on 'Drainage Network should use same as Hydrography in RS_Context'? Did you want the contents of VBETs Drainage Network  to match the contents of Hydrography from RS Context? i.e. same shapefiles, labeling and symbology? 

Exactly. You should have same fcode so should be able to just copy business logic over from RS Context and just point to correct node.

**Comment by joewheaton** [comment]
I think (not sure) this is done? Please take a look @Cashe93

**Comment by Cashe93** [comment]
Yes @joewheaton, it looks like this task was completed back in June.
