### ISSUE TITLE
Update business logic for most rasters to be transparent

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#66]
I'm assigning to @tyler1218hatch and @Cashe93. You two can agree on who will update what on what branches.  Other than hillshades, most (not all) of our rasters should probably default to be transparent (~ `transparency="40"`). See @philipbaileynar example in https://github.com/Riverscapes/RaveAddIn/blob/master/RaveAddIn/XML/topo.xml#L116.

Please update:
- [x] Other [Topo.xml](https://github.com/Riverscapes/RaveAddIn/blob/master/RaveAddIn/XML/topo.xml) project rasters
- [x] Other [rsContext.xml](https://github.com/Riverscapes/RaveAddIn/blob/master/RaveAddIn/XML/rs_context.xml) project rasters
- [x] Other [brat.xml](https://github.com/Riverscapes/RaveAddIn/blob/master/RaveAddIn/XML/brat.xml) project rasters
- [x] Other [vbet.xml](https://github.com/Riverscapes/RaveAddIn/blob/master/RaveAddIn/XML/vbet.xml) project rasters
- [x] Other [hydro.xml](https://github.com/Riverscapes/RaveAddIn/blob/master/RaveAddIn/XML/hydro.xml) project rasters

**Comment by tyler1218hatch** [comment]
[Here's](https://github.com/Riverscapes/RaveAddIn/tree/AddingTransparencies) the branch I'm using for this issue. 

@Cashe93 I'll do BRAT, VBET, and Hydro if you do Topo and rsContext. 
@joewheaton What kind of rasters won't be transparent? Would that be non topographical ones like vegetation data?

**Comment by Cashe93** [comment]
Sounds good @tyler1218hatch. Just to confirm, is it alright to work from the same branch, or do I need to create a separate one?

**Comment by tyler1218hatch** [comment]
I think we should work on the branch together. That should be fine since we're not working on conflicting files. Just let me know when you're finished, then we can do a pull request.

**Comment by Cashe93** [comment]
@tyler1218hatch, how do I access this branch in git Desktop? Should it be an option automatically under the 'Current branch' tab or do I need to pull it from this repository somehow?

**Comment by tyler1218hatch** [comment]
It should just be an option under all of the available branches. Try fetching the origin or closing and reopening github desktop if none of that works.

**Comment by Cashe93** [comment]
@tyler1218hatch it just popped up. Thanks!

**Comment by Cashe93** [comment]
@tyler1218hatch I just committed the changes for both rs_context and topo. Can you see the commits on your end? It's saying I don't have write access so I'm curious to see if it's only committing changes locally.

**Comment by tyler1218hatch** [comment]
I don't see them. I'll try to figure this out soon.

**Comment by Cashe93** [comment]
Sounds good @tyler1218hatch. I've also brought it to the attention of both Joe and Philip so hopefully, it'll be resolved soon.

**Comment by tyler1218hatch** [comment]
From what I can tell, only the master branch has restrictions. So I'm not sure why this one isn't letting you push to it. If you want to send a video of the issue that could help, or we can just wait to hear back from Phillip or Joe.

**Comment by Cashe93** [comment]
Hey @tyler1218hatch, it appears that Philip has resolved the issue. Are you now able to see those commits on your end?

**Comment by tyler1218hatch** [comment]
Yes, I can see them! I’ll finish this up and do a pull request early tomorrow.

**Comment by joewheaton** [comment]
In response to:

> @joewheaton What kind of rasters won't be transparent? Would that be non topographical ones like vegetation data?

Actually, I typically turn on the veg with transparency too (the context of hillshade is really good)... hmmm let me think.  Maybe just make them all and if @CHafen or I figure something out, we'll go from there.

As best I can tell, you guys sorted out other stuff? REmember, if you want us to get the notifications when you mention us use the `@philipbaileynar` instead of just Philip if you want him to see it.
