### ISSUE TITLE
RAVE 1.1.2 & 1.1.3 Broke Topo Projects!

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#73]
## The Problem

CHaMP Topo projects were working great in 1.1.1 and are now broken in 1.1.2 and 1.1.3.  We reproduced this on three different machines. 

I uninstalled RAVE and reinstalled 1.1.1 and it works. I haven't had time to dig into what changed. Teh only thing I noticed is that transparency tags were added and when I open it in VS code, it doesn't like the transparency, which seems weird? This warning is also happening in other projects that are working?

![image](https://user-images.githubusercontent.com/9723905/84734392-f8d8d280-af5d-11ea-8b2a-4761bcb446a3.png)

In field, so sorry not to provide more thorough report here.  Trying to test drive RAVe for folks here and noticed this was broken.

**Comment by joewheaton** [comment]
@philipbaileynar we are in field tomorrow... so no rush on this... just queuing up.

**Comment by joewheaton** [comment]
@philipbaileynar is this sorted now? Can we close it?

**Comment by philipbaileynar** [comment]
I pushed release 1.1.9 today after Steve Bennett encountered a problem with topo projects. 

Please retest with 1.1.9 and close this issue if it works. Post a comment if it's still a problem.

**Comment by philipbaileynar** [comment]
@joewheaton can you please test this again with 1.1.9 and close the issue if it works. Add new comment if it is still broken.

**Comment by joewheaton** [comment]
> @joewheaton can you please test this again with 1.1.9 and close the issue if it works. Add new comment if it is still broken.

Will do.

**Comment by joewheaton** [comment]
Looks to have worked. Thanks!

[![](http://img.youtube.com/vi/lZT7h3ozUSA/0.jpg)](http://www.youtube.com/watch?v=lZT7h3ozUSA "")

A few minor things needing tickets:
- Fix symbology for Topo Grain Size layer files to work over entire expected range of values
- Fix/check inconsisteint shapefiles.
