### ISSUE TITLE
User Experience - RAVE using Yampa - RS Context , BRAT, VBET

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#76]
Hey @philipbaileynar 
As we discussed... here's a [video](https://youtu.be/hvh0yYJ_9SQ) for you (or will be in 33 minutes), which is me going through every output in Yampa RS Context, BRAT and VBET. This is an hour long thing and I didn't tally it, but its probably something on order of 20 issues, most of which are enhancements to bussiness logic symbology. There are some other bigger problems in VBET and BRAT, but you may already be aware of those.  Have fun... shout with questions. Thanks!

[![](http://img.youtube.com/vi/hvh0yYJ_9SQ/0.jpg)](http://www.youtube.com/watch?v=hvh0yYJ_9SQ "")

**Comment by philipbaileynar** [comment]
Pretty sure most of these are complete. Those that aren't are logged as separate issues.
