### ISSUE TITLE
DEM symbology

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#78]
Use the same DEM symbology for BRAT that is in use for Riverscapes Context.

Here's a video in which Joe discovers this issue and requests the change:

https://youtu.be/hvh0yYJ_9SQ?t=1845

**Comment by philipbaileynar** [comment]
@joewheaton Have I captured this correctly? Is your comment about the symbology or the actual DEM data?

**Comment by joewheaton** [comment]
Yes @philipbaileynar, I'm saying just use the DEM layer that we use in other riverscape projects. The confusion about actual DEM data is that the sybmology layer that I use readjusts the elevation range to that currently in the display (which I like), as opposed to the one in there that is spanned to the dataset itself.

**Comment by Cashe93** [comment]
@philipbaileynar it looks like both BRAT and RS_Context business logic are already pulling the same dem.lyr file from the shared folder.

**Comment by joewheaton** [comment]
@Cashe93 they should be, but they're not (see video). The one I want is the one from VBET and RS_Context. See if perhaps we're shipping a layer file of same name in BRAT or something that is overiding.

**Comment by joewheaton** [comment]
Just checking in on status of this @Cashe93 and @wally-mac

**Comment by wally-mac** [comment]
@Cashe93 please look into this.

**Comment by Cashe93** [comment]
@joewheaton  and @wally-mac it appears that this task is complete. I opened up the BRAT project from Joes video as well as an RS_Context project, and both are displaying correctly. Please let me know if this looks correct, or if something else needs to be done. 
![image](https://user-images.githubusercontent.com/49880208/93658512-48b1b480-f9f9-11ea-9441-40d1753d35c8.png) 
![image](https://user-images.githubusercontent.com/49880208/93658545-b52cb380-f9f9-11ea-887f-7f8771ca0593.png)
