### ISSUE TITLE
1.05 might not have been updated everywhere?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#8]
## The Problem

When I installed the [latest 1.05 release](https://github.com/Riverscapes/RaveAddIn/releases/tag/1.0.5), the file I downloaded said 1.05, but on the Install screen, it said it installed 1.04. However, in ArcGIS and in About, it all works and says 1.05. 

File in the "who cares" bin?

**Comment by philipbaileynar** [comment]
You're right. I forgot to update the ESRI config file for the addin.

**Comment by joewheaton** [comment]
Addressed with 1.06.
