### ISSUE TITLE
Symbology for PRISM rasters

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#82]
I just released RAVE version 1.1.6 that includes PRISM climatological rasters in the riverscapes context business logic.

**Note that the only project with these datasets so far is [17060304](https://prism.oregonstate.edu/normals/)**

Please add symbology layer files for these rasters (remembering to add the symbology keys to the business logic XML). I don't know what symbology to use, but perhaps refer to the PRISM web site. Note that you can download the data in PNG format that might serve as a reference for how they prefer to symbolize the data.

https://prism.oregonstate.edu/normals/

Click on the radio button to switch between each PRISM variable and then click the "Download full size image" button to get a PNG of the entire continental US. Hopefully these images have some inspiration for layer symbology.

**Comment by joewheaton** [comment]
@philipbaileynar this  is awesome data. Thanks for building this in. @Cashe93 please do as @philipbaileynar suggests and use the PRISM website as a go by for your symbology and legends (don't forget units too).

**Comment by Cashe93** [comment]
@philipbaileynar, I downloaded the RS_context project for HUC 17060304, but the PRISM datasets appear to be missing. 

![image](https://user-images.githubusercontent.com/49880208/93691850-7275e480-faa8-11ea-9eb5-0dc83ee22496.png)

**Comment by philipbaileynar** [comment]
@Cashe93 try this link:

https://data.riverscapes.xyz/#/Anabranch/3a30cccb-ddda-47c4-8baf-413543c43a78

**Comment by joewheaton** [comment]
@philipbaileynar and @Cashe93 ... just an FYI. These did work for me:
[![](http://img.youtube.com/vi/63TuJJXI9G0/0.jpg)](http://www.youtube.com/watch?v=63TuJJXI9G0 "")

**Comment by Cashe93** [comment]
Thanks @philipbaileynar, that worked. I may have just had an older version of the project.

**Comment by philipbaileynar** [comment]
@Cashe93 your changes are now included in the latest release 1.1.11. Please install and test. Close this issue if the raster layers work. Or comment here if they don't.

**Comment by Cashe93** [comment]
@philipbaileynar I installed the latest version and everything looks groovy. Closing this issue now.
