### ISSUE TITLE
Fix why some Channel Units show up and some don't in Topo Surveys

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#87]
## The Problem
From end of #73 we need Fix or figure out why some channel unit shapefiles show up in some topos and not in others.
## Reproduction steps
See towards [end of video](https://youtu.be/lZT7h3ozUSA?t=415)
[![](http://img.youtube.com/vi/lZT7h3ozUSA/0.jpg)](http://www.youtube.com/watch?v=lZT7h3ozUSA?t=415 "")

**Comment by philipbaileynar** [comment]
This is a problem with the data, not RAVE.

The RAVE channel unit symbology is expecting certain fields to be present in the channel unit ShapeFiles but these fields are not always present. 

CHaMP grain size fields (e.g. D50) were collected as Aux measurements (on Allegro and then iPad) and are not part of the topo data collection. These fields got transferred to the ShapeFiles for some but not all field seasons (as topo and cm.org processing evolved other time.)

So the solution here is to trawl all CHaMP surveys, find the ShapeFiles that are missing the fields, then go find the grain size values and write them to the ShapeFiles.

I'm closing this for RAVE. This is a data management task that is probably best funded on a watershed by watershed basis (e.g. Asotin IMW).

**Comment by joewheaton** [comment]
@philipbaileynar, instead of closing issues like this that are rightly somewhere else, can we leave them open and move them to something else (e.g. a warehouse repo)?

Message received on the solution. Lets queue it up as unfunded.

**Comment by philipbaileynar** [comment]
Agreed. 

This one is a special case and doesn't really have a home. 

What's really needed is a new tool that talks to the champ workbench and enriches the topo data with both measurements and metrics. 

This tool doesn't exist right now and so I don't know where to put the issue.
