### ISSUE TITLE
Who so fast? Really nice Basemaps.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#9]
I just checked out the new [1.05 basemaps feature](http://rave.riverscapes.xyz/base-maps.html). It works flawlessly. **My question is why is this so much faster then adding the WMS from ESRI's Add layer (other than just the navigation steps)?** What I mean, is it seems really snappy. Maybe its just perception...

[![](http://img.youtube.com/vi/JeZyRajOjd4/0.jpg)](http://www.youtube.com/watch?v=JeZyRajOjd4 "")

**Comment by philipbaileynar** [comment]
Could it be that you're typically zoomed out when you do the Esri approach. But with rave you've already added your project and one or two layers. The first time it retrieves the WMS data it only needs a tiny rectangle. 

Other than that, no idea...
