### ISSUE TITLE
Questions about business logic for inundation projects

### ISSUE THREAD

**Issue by kbartelt** [Riverscapes/RaveAddIn#90]
Hi @MattReimer @philipbaileynar @joewheaton  

I have some questions/ issues about the inundation business logic that I typed below and also demonstrated in a video

1. Issues using repeater tag in business logic
2. Within the business logic can I point to a project metadata tag in the project xml for a node label?
3. Everything loads in the correct order in the RAVE Project Explorer, but then the order gets messed up if I load multiple things at once into the ArcMap TOC
4. I have an error in all my project.rs.xml files in which the project xml path points to a .tif but the file is actually a .png. Is there any way to fix this and bring this file into RAVE without going in and fixing each project.rs.xml file?

Thank you

[Here is a video demonstrating the above ](https://youtu.be/CpvSGdCHzkA)

[link to data folder](https://usu.box.com/s/qq43d65smira6c6qqdzkinmcsel3on4e)

<iframe width="560" height="315" src="https://www.youtube.com/embed/CpvSGdCHzkA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by joewheaton** [comment]
Thanks @kbartelt for posting this. @philipbaileynar Karen is about to submit her thesis. The timing of above is something she'll need to resolve in November in preparation for submitting her manuscript.

**Comment by philipbaileynar** [comment]
1. I think repeaters are broken in RAVE. I tried using them a while back and couldn't get them to work as expected. We need an issue for that.
1. No. You cannot refer to metadata within a node label. Log that as an enhancement issue if that's required.
1. Adding layers to the map in incorrect order is a [know issue](https://github.com/Riverscapes/RaveAddIn/issues/35).
1. You will need to fix your project files. If there are less than 20 then just suck it up and edit them by hand. If there are more than 20 then consider a one-time hacky Python script to make the change.

**Comment by kbartelt** [comment]
@philipbaileynar @MattReimer @joewheaton FYI the repeaters appear to be working fine with RAVE for how I was using them, the issue I was having was within the project XML

**Comment by joewheaton** [comment]
Great news Karen!
_____________________
Dr. Joseph M. Wheaton
435-554-1247 (direct) | http://www.joewheaton.org
