### ISSUE TITLE
Missing Confinement Values

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#91]
I think this is a problem with the confinement symbology, not the confinement model itself. I ran 17060304 and loaded the confinement margins in ArcMap. Noticed a reach that was absent from the map. This typically means that it was omitted from the layer symbology.

|Case|Confinement Ratio|Constriction Ratio|
|---|---|---|
|Absent Reach|1|10|
|Green Reaches|0|0|

<img width="1551" alt="Screen Shot 2020-10-28 at 2 36 49 PM" src="https://user-images.githubusercontent.com/8645379/97499488-2893e000-192b-11eb-91d9-fe5a1461d0e4.png">

Please fix and re-upload relevant layer files.

**Comment by philipbaileynar** [comment]
@KellyMWhitehead did we ever figure this out?

**Comment by KellyMWhitehead** [comment]
Issue was related to geometry tolerance when splitting the confinement buffer by the centerline. Was able to extend the splitting lines by using "scale" and seems to work for all polygons so far.

Fixed: 18a0ba0a2cdb15a98dde60aa3c3bb2f9a312ca1d
