### ISSUE TITLE
RCAT Vegetation Not Displaying (1.1.15)

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/RaveAddIn#97]
I was expecting something like this might happen. This was working fine on my end last night, but there's some issue here. Maybe it's having trouble pulling from the shared symbology? Note, it's not like the symbology is wrong, it's that there's some error before the raster is even displayed.
![image](https://user-images.githubusercontent.com/27084463/98324766-c8e4a700-1fb2-11eb-892b-42fe9d623e59.png)

**Comment by philipbaileynar** [comment]
The red exclamation means it can't find the raster on disk. Either file isn't there, or the path that is built by concatenating folders from the business logic is wrong.

**Comment by tyler1218hatch** [comment]
@philipbaileynar Nevermind, this is my mistake. It is an issue with the data on box. Thanks!
